# Generated by Django 2.0.1 on 2018-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180711_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
