# Generated by Django 2.0.1 on 2018-07-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
    ]
