# Generated by Django 2.0 on 2018-08-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
