# Generated by Django 2.0 on 2018-08-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-rating',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
